export { default } from "next-auth/middleware";

export const config = {
  matcher: [
    "/dashboard",
    "/admin",
    "/size",
    "/color",
    "/product",
    "/inventory",
    "/blog",
    "/category",
    "/coupon",
    "/customer",
    "/collection",
    "/order",
    "/promotebanner",
    "/mainbanner",
    "/order-detail/:path*",
    "/account",
    "/add-admin",
    "/add-category",
    "/add-blog",
    "/add-color",
    "/add-coupon",
    "/add-customer",
    "/add-mainbanner",
    "/add-product",
    "/add-size",
    "/edit-product/:path*",
    "/edit-admin/:path*",
    "/edit-blog/:path*",
    "/edit-category/:path*",
    "/edit-color/:path*",
    "/edit-coupon/:path*",
    "/edit-customer/:path*",
    "/edit-size/:path*",
  ],
}; // những trang cần đăng nhập với được truy cập
